org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
fabric_loader_version=0.19.3
fabric_api_version=0.116.14+1.21.1
fabric_kotlin_version=1.13.11+kotlin.2.3.21
cobblemon_version_id=kF7CvxTo
mega_showdown_version_id=ch7DfnXP
owo_lib_version_id=JB1fLQnc
architectury_api_version_id=Pzc2FP5K
accessories_version_id=Xlt4eWBe

better_battle_presentation_version=1.2.2
better_cobblemon_music_version=1.2.6
cobblemon_custom_species_version=1.0.0
more_battle_content_version=1.6.17
more_battle_content_better_ai_version=1.2.10
player_popup_emotes_version=1.0.9
simple_myroom_version=1.3.0
maven_group=jbro.cobblemon.morebattlecontent
