org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
fabric_loader_version=0.19.5
fabric_api_version=0.116.17+1.21.1
fabric_kotlin_version=1.14.1+kotlin.2.4.20
cobblemon_version_id=gBW3vLC7
cobblemon_maven_version=1.8.1+1.21.1
mega_showdown_version_id=TKdAixuR
owo_lib_version_id=JB1fLQnc
architectury_api_version_id=Pzc2FP5K
accessories_version_id=Xlt4eWBe

better_battle_presentation_version=1.2.3
better_cobblemon_battlecam_version=0.1.0
better_cobblemon_music_version=1.2.7
cobblemon_battle_ui_version=0.1.2
cobblemon_custom_species_version=1.0.1
font_glyph_race_fix_version=1.0.0
more_battle_content_version=1.6.21
more_battle_content_better_ai_version=1.2.16
player_popup_emotes_version=1.0.9
pokefusion_version=1.2.4
rounding_block_version=1.1.0
simple_myroom_version=1.3.0
maven_group=jbro.cobblemon.morebattlecontent
