"""Every kind of wild trainer: its name, the RCT Trainers+ skin classes it wears, where and when it appears, its tier
and the Pokemon lines it trains. Each species names the first stage a trainer may use; the generator follows its
evolutions from Cobblemon's data, so later stages appear at the levels they evolve at."""

D, N = "day", "night"

PLAINS = ["#cobblemon:is_plains", "#cobblemon:is_grassland"]
FOREST = ["#cobblemon:is_forest"]
JUNGLE = ["#cobblemon:is_jungle"]
TAIGA = ["#cobblemon:is_taiga"]
SAVANNA = ["#cobblemon:is_savanna"]
MOUNTAIN = ["#cobblemon:is_mountain", "#cobblemon:is_hills"]
PEAK = ["#cobblemon:is_peak", "#cobblemon:is_highlands"]
BADLANDS = ["#cobblemon:is_badlands"]
DESERT = ["#cobblemon:is_desert", "#cobblemon:is_arid"]
SNOW = ["#cobblemon:is_snowy", "#cobblemon:is_freezing", "#cobblemon:is_snowy_forest", "#cobblemon:is_snowy_taiga", "#cobblemon:is_glacial"]
BEACH = ["#cobblemon:is_beach", "#cobblemon:is_coast"]
STONY = ["#cobblemon:is_stony_beach"]
RIVER = ["#cobblemon:is_river", "#cobblemon:is_freshwater"]
SWAMP = ["#cobblemon:is_swamp"]
SPOOKY = ["#cobblemon:is_spooky"]
FLORAL = ["#cobblemon:is_floral", "#cobblemon:is_cherry_blossom"]
MAGICAL = ["#cobblemon:is_magical"]
MUSHROOM = ["#cobblemon:is_mushroom"]
VOLCANIC = ["#cobblemon:is_volcanic", "#cobblemon:is_thermal"]
BAMBOO = ["#cobblemon:is_bamboo"]
TROPICAL = ["#cobblemon:is_tropical_island", "#cobblemon:is_island"]
SHRUB = ["#cobblemon:is_shrubland", "#cobblemon:is_plateau"]
ANY = ["#cobblemon:is_overworld"]


def K(id, ko, en, skins, biomes, time, species, tier="normal"):
    return dict(id=id, ko=ko, en=en, skins=skins.split(), biomes=biomes, time=time, species=species.split(), tier=tier)


NORMAL = [
    # Roadside regulars
    K("youngster", "반바지 꼬마", "Youngster", "youngster", PLAINS + FOREST, D,
      "rattata sentret zigzagoon bidoof pidgey nidoranm ekans lillipup patrat yungoos skwovet wooloo"),
    K("lass", "짧은 치마", "Lass", "lass", PLAINS + FLORAL, D,
      "jigglypuff clefairy skitty oddish marill buneary nidoranf flabebe snubbull minccino fidough"),
    K("bug_catcher", "곤충채집 소년", "Bug Catcher", "bug_catcher", FOREST + JUNGLE, D,
      "caterpie weedle wurmple kricketot venonat paras ledyba spinarak nincada scatterbug sewaddle dewpider"),
    K("bug_maniac", "곤충마니아", "Bug Maniac", "bug", FOREST + JUNGLE + SWAMP, N,
      "pinsir heracross scyther yanma shuckle shelmet karrablast dwebble joltik skorupi venipede cutiefly tarountula"),
    K("picnicker", "피크닉걸", "Picnicker", "picnicker", PLAINS + SAVANNA + FOREST, D,
      "marill ponyta bellsprout pikachu meowth mareep cherubi eevee hoppip skiddo fomantis"),
    K("camper", "캠핑보이", "Camper", "camper", FOREST + TAIGA + PLAINS, D,
      "growlithe poochyena zubat psyduck shinx teddiursa sandshrew hoothoot yamper nickit"),
    K("school_kid", "학원 아이", "School Kid", "school_kid", PLAINS + FOREST, D,
      "oddish sunkern shroomish budew seedot bellsprout pikachu tangela exeggcute foongus"),
    K("poke_kid", "포켓몬 꼬마", "Poké Kid", "poke_kid", PLAINS + FOREST, D,
      "pichu cleffa igglybuff togepi happiny munchlax bonsly mimejr budew riolu"),
    K("pokefan", "포켓몬 애호가", "Poké Fan", "poke_fan pokefan", PLAINS + FLORAL, D,
      "pikachu clefairy jigglypuff snubbull skitty plusle minun pachirisu dedenne togepi marill emolga"),
    K("trainer", "트레이너", "Trainer", "trainer", ANY, None,
      "pidgey rattata pikachu eevee growlithe ponyta magikarp geodude oddish abra machop gastly"),
    K("twins", "쌍둥이", "Twins", "twins", PLAINS + FLORAL, D,
      "plusle minun volbeat illumise solrock lunatone seviper zangoose throh sawk nidoranm nidoranf"),
    K("young_couple", "젊은 커플", "Young Couple", "young_couple", PLAINS + FLORAL, D,
      "luvdisc volbeat illumise nidoranf nidoranm pikachu eevee skitty minccino deerling milcery"),
    K("breeder", "포켓몬 브리더", "Pokémon Breeder", "breeder pokemon_breeder", PLAINS + FLORAL, None,
      "pichu cleffa igglybuff togepi tyrogue smoochum elekid magby azurill wynaut budew chingling happiny mantyke riolu"),
    K("cyclist", "사이클리스트", "Cyclist", "cyclist", PLAINS + SAVANNA, D,
      "doduo ponyta electrike shinx zigzagoon starly blitzle pidove fletchling cyclizar"),
    K("jogger", "조깅맨", "Jogger", "jogger", PLAINS + FOREST, D,
      "doduo ponyta tauros zigzagoon lillipup blitzle deerling skiddo yamper wooloo nickit"),
    K("triathlete", "트라이애슬론 선수", "Triathlete", "jogger cyclist", PLAINS + BEACH, D,
      "doduo buizel ponyta tentacool electrike marill starly pidove wingull arrokuda finizen"),
    # Mountains and rock
    K("hiker", "등산가", "Hiker", "hiker", MOUNTAIN + PEAK + BADLANDS, None,
      "geodude onix machop rhyhorn roggenrola aron nosepass rolycoly diglett sandshrew nacli"),
    K("backpacker", "배낭여행자", "Backpacker", "hiker camper", MOUNTAIN + TAIGA, D,
      "nosepass bonsly rockruff skiddo stantler mudbray rolycoly tinkatink flittle"),
    K("mountain_guide", "산악 안내인", "Mountain Guide", "hiker ranger", PEAK + MOUNTAIN, D,
      "noibat rufflet starly taillow rookidee cufant bergmite skarmory gligar"),
    K("miner", "광부", "Miner", "worker hiker", MOUNTAIN + BADLANDS, None,
      "drilbur roggenrola onix geodude aron nosepass carbink rolycoly nacli glimmet"),
    K("worker", "작업원", "Worker", "worker", MOUNTAIN + BADLANDS + PLAINS, D,
      "machop timburr roggenrola geodude onix drilbur rolycoly nacli silicobra tinkatink"),
    K("engineer", "엔지니어", "Engineer", "engineer", MOUNTAIN + BADLANDS, D,
      "magnemite klink bronzor aron nosepass varoom tinkatink klefki tadbulb orthworm"),
    K("blacksmith", "대장장이", "Blacksmith", "worker engineer", VOLCANIC + MOUNTAIN, None,
      "magby slugma heatmor honedge klefki tinkatink pawniard litwick sizzlipede varoom"),
    K("climber", "설산 등반가", "Climber", "hiker skier", SNOW + PEAK, None,
      "snorunt bergmite cubchoo amaura snom vanillite sneasel swinub cetoddle cryogonal"),
    K("gatekeeper", "문지기", "Gatekeeper", "gatekeeper", MOUNTAIN + PLAINS, None,
      "bonsly onix golett bronzor carbink stonjourner klefki honedge sudowoodo"),
    # Fighting
    K("black_belt", "태권왕", "Black Belt", "black_belt", MOUNTAIN + PLAINS, None,
      "machop mankey makuhita meditite tyrogue riolu timburr croagunk mienfoo throh sawk pancham"),
    K("battle_girl", "배틀걸", "Battle Girl", "battle_girl", PLAINS + MOUNTAIN, D,
      "meditite mankey riolu mienfoo crabrawler hawlucha stufful clobbopus tyrogue makuhita"),
    K("crush_girl", "격투 소녀", "Crush Girl", "crush_girl", MOUNTAIN + PLAINS, D,
      "machop makuhita meditite mankey riolu mienfoo hawlucha crabrawler pancham clobbopus stufful"),
    K("cue_ball", "스킨헤드", "Cue Ball", "cue_ball", BADLANDS + MOUNTAIN, N,
      "machop mankey primeape makuhita throh sawk grimer koffing scraggy tyrogue"),
    K("monk", "수도승", "Monk", "black_belt cue_ball", MOUNTAIN + BAMBOO, None,
      "meditite pancham mienfoo riolu tyrogue makuhita throh sawk falinks timburr"),
    # Birds and sky
    K("bird_keeper", "새조련사", "Bird Keeper", "bird_keeper", PLAINS + MOUNTAIN + SAVANNA, D,
      "pidgey spearow doduo starly hoothoot taillow swablu natu pidove rookidee pikipek fletchling"),
    K("sky_watcher", "하늘 관측가", "Sky Watcher", "bird_keeper super_nerd", PEAK + MOUNTAIN, None,
      "hoothoot natu swablu murkrow noibat pikipek rufflet wingull tropius chatot sigilyph flamigo"),
    # Water
    K("swimmer", "수영선수", "Swimmer", "swimmer swimmerm", BEACH, D,
      "tentacool goldeen staryu horsea poliwag buizel seel wingull mantine finneon wimpod"),
    K("swimmer_girl", "수영 아가씨", "Swimmer Girl", "swimmerf", BEACH, D,
      "staryu shellder corsola luvdisc clamperl frillish psyduck marill spheal lapras"),
    K("tuber", "튜브 꼬마", "Tuber", "tuber", BEACH + RIVER, D,
      "psyduck marill wooper surskit lotad chewtle wiglett buizel wingull krabby"),
    K("surfer", "서퍼", "Surfer", "swimmerm swimmer", BEACH, D,
      "wingull tentacool horsea buizel mantine remoraid finneon chinchou finizen wailmer"),
    K("diver", "다이버", "Diver", "swimmer swimmerf", BEACH + STONY, None,
      "clamperl relicanth chinchou corsola qwilfish mareanie pyukumuku dhelmise wishiwashi shellder"),
    K("fisherman", "낚시꾼", "Fisherman", "fisher fisherman", RIVER + BEACH + SWAMP, None,
      "magikarp goldeen remoraid barboach carvanha finneon wooper krabby chinchou arrokuda"),
    K("angler", "낚시광", "Angler", "fisher", RIVER + SWAMP, N,
      "barboach feebas basculin stunfisk wishiwashi chewtle arrokuda tatsugiri goldeen poliwag"),
    K("sailor", "뱃사람", "Sailor", "sailor", BEACH + STONY, None,
      "machop tentacool wingull krabby psyduck poliwag wailmer shellder skrelp clauncher"),
    K("captain", "선장", "Captain", "sailor gentleman", BEACH + STONY, None,
      "tentacool krabby corphish wailmer carvanha skrelp clauncher dhelmise arrokuda bruxish"),
    K("lighthouse_keeper", "등대지기", "Lighthouse Keeper", "sailor worker", BEACH + STONY, N,
      "chinchou mareep magnemite wingull shinx electrike tynamo joltik tadbulb"),
    K("parasol_lady", "파라솔 아가씨", "Parasol Lady", "parasol_lady", BEACH, D,
      "drifloon wingull lotad surskit marill psyduck spheal frillish sunkern hoppip"),
    # Grass and flowers
    K("aroma_lady", "아로마 아가씨", "Aroma Lady", "aroma_lady", FLORAL + FOREST, D,
      "oddish budew bellsprout sunkern hoppip cherubi petilil flabebe comfey smoliv bounsweet"),
    K("florist", "꽃집 아가씨", "Florist", "aroma_lady lass", FLORAL, D,
      "budew oddish comfey flabebe cottonee petilil deerling sunkern bounsweet fomantis smoliv"),
    K("gardener", "정원사", "Gardener", "worker picnicker", PLAINS + FLORAL + FOREST, D,
      "seedot lotad shroomish bellsprout tangela exeggcute cacnea tropius sewaddle foongus bounsweet"),
    K("farmer", "농부", "Farmer", "rancher ranchers worker", PLAINS, D,
      "miltank mareep lechonk wooloo sunkern seedot deerling bouffalant skiddo tauros"),
    K("beekeeper", "양봉가", "Beekeeper", "worker bug_catcher", FLORAL + FOREST, D,
      "combee cutiefly volbeat illumise wurmple caterpie heracross nincada ledyba"),
    K("lumberjack", "나무꾼", "Lumberjack", "worker", FOREST + TAIGA, D,
      "timburr phantump bonsly pinsir heracross seedot pikipek sewaddle"),
    K("mushroom_picker", "버섯 채집가", "Mushroom Picker", "picnicker camper", MUSHROOM + FOREST + SWAMP, None,
      "paras shroomish foongus morelull toedscool phantump bounsweet"),
    # Fire
    K("kindler", "불꽃소년", "Kindler", "camper", VOLCANIC + BADLANDS + SAVANNA, None,
      "growlithe vulpix ponyta magby slugma numel torkoal houndour litleo salandit sizzlipede charcadet"),
    K("fire_breather", "불꽃 곡예사", "Fire Breather", "juggler", VOLCANIC + BADLANDS, N,
      "koffing vulpix magby slugma numel torkoal heatmor litwick darumaka fletchling"),
    # Electric and machines
    K("rocker", "로커", "Rocker", "rocker", PLAINS + SAVANNA, N,
      "voltorb magnemite electrike shinx toxel pikachu blitzle tynamo noibat"),
    K("guitarist", "기타리스트", "Guitarist", "guitarist", PLAINS + SAVANNA, D,
      "electrike shinx elekid toxel tynamo joltik voltorb emolga plusle minun pachirisu dedenne morpeko"),
    K("musician", "음악가", "Musician", "guitarist rocker", PLAINS + FLORAL, None,
      "chatot kricketot whismur chingling jigglypuff toxel noibat jangmoo"),
    K("super_nerd", "괴짜", "Super Nerd", "super_nerd", PLAINS + MOUNTAIN, N,
      "magnemite voltorb grimer koffing porygon ditto klink rotom bronzor"),
    K("scientist", "과학자", "Scientist", "scientist", ANY, N,
      "magnemite voltorb koffing grimer elekid magby beldum klink porygon ditto tynamo"),
    K("astronomer", "천문학자", "Astronomer", "super_nerd psychic", ANY, N,
      "clefairy lunatone solrock bronzor elgyem staryu beldum chingling munna"),
    K("weather_researcher", "기상 연구원", "Weather Researcher", "scientist", PLAINS + DESERT + SNOW, D,
      "drifloon snorunt hippopotas pelipper wingull tyrunt amaura cherubi"),
    # Psychic and ghost
    K("psychic", "초능력자", "Psychic", "psychic", ANY, N,
      "abra drowzee natu ralts spoink slowpoke bronzor espurr girafarig munna gothita solosis"),
    K("channeler", "영매", "Channeler", "channeler", SPOOKY + SWAMP + TAIGA, N,
      "gastly misdreavus duskull shuppet drifloon litwick yamask sableye phantump pumpkaboo sinistea honedge"),
    K("hex_maniac", "오컬트마니아", "Hex Maniac", "channeler psychic", SPOOKY + SWAMP, N,
      "gastly misdreavus shuppet duskull drifloon litwick frillish honedge phantump sandygast mimikyu sinistea"),
    K("shrine_maiden", "무녀", "Shrine Maiden", "channeler lady", FLORAL + BAMBOO, None,
      "vulpix misdreavus natu chingling spoink sableye espurr ralts poltchageist"),
    K("fortune_teller", "점술가", "Fortune Teller", "psychic madame", ANY, N,
      "natu chingling spoink misdreavus murkrow sigilyph elgyem hatenna indeedee"),
    # Poison, dark and the streets
    K("biker", "폭주족", "Biker", "biker", BADLANDS + PLAINS, N,
      "grimer koffing zubat trubbish scraggy stunky sandile houndour poochyena varoom"),
    K("roughneck", "불량배", "Roughneck", "roughneck biker", BADLANDS + MOUNTAIN, N,
      "scraggy pawniard sandile croagunk stunky nickit impidimp purrloin"),
    K("gambler", "겜블러", "Gambler", "gambler", PLAINS + SAVANNA, N,
      "meowth glameow purrloin sneasel murkrow stunky spinda zorua"),
    K("ninja_boy", "닌자 소년", "Ninja Boy", "ninja_boy", FOREST + JUNGLE + BAMBOO, N,
      "koffing venonat voltorb zubat nincada kecleon shuppet sneasel zorua purrloin"),
    K("swamp_explorer", "늪지 탐험가", "Swamp Explorer", "camper hiker", SWAMP, None,
      "wooper lotad croagunk stunfisk shroomish barboach grimer chewtle skorupi"),
    # Cities and manners
    K("gentleman", "신사", "Gentleman", "gentleman", PLAINS + FOREST, D,
      "growlithe houndour snubbull lillipup rockruff yamper espurr meowth bronzor"),
    K("madame", "마담", "Madame", "madame", PLAINS + FLORAL, D,
      "skitty glameow snubbull espurr meowth purrloin furfrou milcery swirlix spritzee"),
    K("socialite", "사교계 명사", "Socialite", "madame lady", FLORAL, D,
      "skitty glameow espurr furfrou swirlix spritzee milcery ponyta vulpix deerling"),
    K("lady", "아가씨", "Lady", "lady", PLAINS + FLORAL, D,
      "skitty snubbull minccino espurr meowth buneary swirlix spritzee fidough"),
    K("beauty", "미인", "Beauty", "beauty", BEACH + FLORAL + PLAINS, D,
      "vulpix ponyta glameow minccino deerling milcery feebas luvdisc skitty flabebe"),
    K("rich_boy", "도련님", "Rich Boy", "rich_boy", PLAINS + FOREST, D,
      "growlithe ponyta vulpix eevee shinx lillipup deerling rockruff fidough"),
    K("waitress", "웨이트리스", "Waitress", "waitress", PLAINS + FLORAL, D,
      "milcery swirlix cherubi bounsweet applin fidough smoliv minccino happiny cutiefly"),
    K("baker", "제빵사", "Baker", "waitress worker", PLAINS, D,
      "fidough milcery swirlix applin cherubi bounsweet smoliv lechonk"),
    K("police_officer", "경찰관", "Police Officer", "police_officer", PLAINS + ANY, N,
      "growlithe houndour lillipup rockruff yamper electrike shinx riolu poochyena maschiff"),
    K("artist", "예술가", "Artist", "artist", PLAINS + FLORAL, D,
      "smeargle spinda kecleon flabebe scatterbug furfrou minccino audino tatsugiri"),
    K("painter", "화가", "Painter", "painter", PLAINS + FLORAL, D,
      "smeargle lotad sunkern budew scatterbug comfey skiddo deerling"),
    K("dancer", "댄서", "Dancer", "beauty crush_girl", PLAINS + FLORAL, None,
      "meditite oddish spinda lotad tyrogue cutiefly ralts flittle"),
    K("juggler", "저글러", "Juggler", "juggler", PLAINS + SAVANNA, None,
      "voltorb drowzee mimejr koffing magnemite baltoy bronzor solrock lunatone spoink"),
    K("clown", "피에로", "Clown", "clown juggler", PLAINS + FLORAL, N,
      "mimejr wynaut spinda sableye impidimp morelull pumpkaboo"),
    K("collector", "콜렉터", "Collector", "collector", ANY, None,
      "eevee kangaskhan tauros farfetchd lapras sableye mawile relicanth spiritomb pinsir"),
    K("pokemaniac", "괴수마니아", "PokéManiac", "pokemaniac", MOUNTAIN + SWAMP, N,
      "rhyhorn cubone slowpoke nidoranm lickitung aron axew druddigon tyrunt kangaskhan"),
    # Ranches and the wild
    K("rancher", "목장주", "Rancher", "rancher ranchers", PLAINS + SAVANNA, D,
      "mareep wooloo miltank tauros skiddo lechonk mudbray bouffalant ponyta"),
    K("cowgirl", "카우걸", "Cowgirl", "cowgirl", SAVANNA + BADLANDS + DESERT, D,
      "ponyta tauros sandile mudbray blitzle growlithe ekans sandshrew cacnea"),
    K("tamer", "조련사", "Tamer", "tamer", SAVANNA + BADLANDS, D,
      "ekans sandile zangoose seviper meowth poochyena litleo tauros mudbray skiddo"),
    K("safari_guide", "사파리 가이드", "Safari Guide", "ranger pokemon_ranger", SAVANNA, D,
      "tauros girafarig rhyhorn litleo blitzle mudbray kangaskhan nidoranf phanpy skiddo"),
    K("pokemon_ranger", "포켓몬 레인저", "Pokémon Ranger", "pokemon_ranger", JUNGLE + FOREST + TAIGA + SAVANNA, None,
      "pikachu bulbasaur chikorita treecko shinx growlithe teddiursa tropius starly buneary"),
    K("ranger", "숲지기", "Forest Ranger", "ranger", TAIGA + SNOW + FOREST, None,
      "sneasel snorunt swinub stantler teddiursa vulpix skiddo deerling cubchoo vanillite"),
    K("jungle_explorer", "정글 탐험가", "Jungle Explorer", "pokemon_ranger camper", JUNGLE + TROPICAL, None,
      "aipom tropius pikipek bounsweet hawlucha pansage pansear panpour yungoos fomantis sewaddle"),
    K("desert_wanderer", "사막 방랑자", "Desert Wanderer", "ruin_maniac cowgirl", DESERT, None,
      "cacnea sandile trapinch hippopotas maractus silicobra numel sandshrew dwebble skorupi"),
    K("ruin_maniac", "유적마니아", "Ruin Maniac", "ruin_maniac ruin_mamoac", DESERT + BADLANDS, None,
      "baltoy cubone trapinch hippopotas sandile yamask sigilyph bronzor golett elgyem"),
    K("archaeologist", "고고학자", "Archaeologist", "ruin_maniac scientist", DESERT + BADLANDS, D,
      "omanyte kabuto aerodactyl lileep anorith cranidos shieldon tirtouga archen tyrunt amaura"),
    K("skier", "스키어", "Skier", "skier", SNOW, None,
      "swinub snorunt cryogonal spheal cubchoo bergmite vanillite smoochum sneasel delibird cetoddle snom"),
    K("boarder", "보더", "Boarder", "skier", SNOW + PEAK, D,
      "sneasel swinub snorunt delibird bergmite cubchoo vanillite snom cetoddle cryogonal"),
    K("shepherd", "양치기", "Shepherd", "rancher camper", PLAINS + MOUNTAIN, D,
      "mareep wooloo lillipup rockruff skiddo stantler growlithe houndour"),
    K("naturalist", "자연 관찰가", "Naturalist", "picnicker pokemon_ranger", FOREST + FLORAL, D,
      "caterpie ledyba hoppip sewaddle deerling pikipek bounsweet skwovet nymble tarountula"),
    K("island_kid", "섬마을 아이", "Island Kid", "tuber school_kid", TROPICAL + BEACH, D,
      "exeggcute wingull pikipek yungoos mareanie wishiwashi pyukumuku bounsweet salandit cutiefly"),
    K("moor_walker", "황야 산책자", "Moor Walker", "gentleman jogger", SHRUB + PLAINS, None,
      "nickit wooloo rookidee skwovet yamper rolycoly chewtle nymble gossifleur"),
    K("bamboo_hermit", "대숲 은둔자", "Bamboo Hermit", "black_belt ninja_boy", BAMBOO, None,
      "pancham bonsly shroomish ninjask spinda kecleon tangela tyrogue"),
    K("mage", "마법 연구가", "Mage", "psychic painter", MAGICAL + FLORAL, N,
      "clefairy togepi ralts spritzee swirlix flabebe hatenna impidimp cottonee"),
    K("hot_spring_keeper", "온천지기", "Hot Spring Keeper", "waitress worker", VOLCANIC + MOUNTAIN, None,
      "slugma numel torkoal magby salandit sizzlipede carkol charcadet"),
]

ACE = [
    K("ace_trainer", "엘리트 트레이너", "Ace Trainer", "ace_trainer", ANY, None,
      "growlithe lapras munchlax absol riolu magikarp togepi ralts beldum heracross scyther eevee", "ace"),
    K("veteran", "베테랑", "Veteran", "veteran", ANY, None,
      "machop gastly abra tauros kangaskhan lapras munchlax growlithe staryu rhyhorn nidoranm exeggcute", "ace"),
    K("dragon_tamer", "드래곤 조련사", "Dragon Tamer", "dragon_tamer", PEAK + MOUNTAIN, None,
      "dratini bagon gible swablu axew deino noibat horsea druddigon goomy jangmoo dreepy", "ace"),
    K("normal_ace", "노말 엘리트", "Normal Ace", "ace_trainer mega_trainer", PLAINS, None,
      "tauros kangaskhan munchlax porygon eevee zangoose lillipup buneary minccino skwovet lechonk", "ace"),
    K("fire_ace", "불꽃 엘리트", "Fire Ace", "ace_trainer mega_trainer", VOLCANIC + BADLANDS + SAVANNA, None,
      "growlithe ponyta magby houndour torkoal litleo larvesta salandit sizzlipede charcadet heatmor vulpix", "ace"),
    K("water_ace", "물 엘리트", "Water Ace", "ace_trainer mega_trainer", BEACH + RIVER, None,
      "magikarp lapras staryu horsea totodile mudkip carvanha spheal buizel froakie wimpod finizen", "ace"),
    K("grass_ace", "풀 엘리트", "Grass Ace", "ace_trainer mega_trainer", FOREST + JUNGLE + FLORAL, None,
      "bulbasaur chikorita treecko turtwig snivy chespin rowlet grookey budew bounsweet petilil tropius", "ace"),
    K("electric_ace", "전기 엘리트", "Electric Ace", "ace_trainer mega_trainer", PLAINS + SAVANNA, None,
      "pikachu magnemite elekid mareep shinx blitzle tynamo rotom toxel electrike tadbulb joltik", "ace"),
    K("ice_ace", "얼음 엘리트", "Ice Ace", "ace_trainer mega_trainer", SNOW, None,
      "lapras sneasel swinub snorunt spheal snom vanillite cubchoo bergmite amaura cetoddle cryogonal", "ace"),
    K("fighting_ace", "격투 엘리트", "Fighting Ace", "ace_trainer veteran", MOUNTAIN, None,
      "machop tyrogue riolu makuhita meditite timburr mienfoo hawlucha pancham crabrawler falinks heracross", "ace"),
    K("poison_ace", "독 엘리트", "Poison Ace", "ace_trainer mega_trainer", SWAMP + JUNGLE, None,
      "nidoranm nidoranf zubat grimer gastly croagunk skorupi venipede trubbish skrelp mareanie glimmet", "ace"),
    K("ground_ace", "땅 엘리트", "Ground Ace", "ace_trainer veteran", DESERT + BADLANDS, None,
      "rhyhorn cubone gligar phanpy trapinch hippopotas gible drilbur sandile mudbray silicobra", "ace"),
    K("flying_ace", "비행 엘리트", "Flying Ace", "ace_trainer mega_trainer", PEAK + MOUNTAIN + PLAINS, None,
      "pidgey starly fletchling rookidee skarmory aerodactyl swablu rufflet hawlucha noibat tropius", "ace"),
    K("psychic_ace", "에스퍼 엘리트", "Psychic Ace", "ace_trainer mega_trainer", ANY, N,
      "abra ralts beldum slowpoke espurr elgyem gothita solosis hatenna natu girafarig", "ace"),
    K("bug_ace", "벌레 엘리트", "Bug Ace", "ace_trainer mega_trainer", FOREST + JUNGLE, None,
      "scyther heracross pinsir shuckle yanma larvesta joltik karrablast shelmet nymble venipede", "ace"),
    K("rock_ace", "바위 엘리트", "Rock Ace", "ace_trainer veteran", MOUNTAIN + BADLANDS, None,
      "larvitar onix aerodactyl cranidos shieldon tyrunt amaura rockruff carbink nacli rolycoly", "ace"),
    K("ghost_ace", "고스트 엘리트", "Ghost Ace", "ace_trainer mega_trainer", SPOOKY + SWAMP, N,
      "gastly misdreavus duskull litwick honedge phantump mimikyu dreepy sinistea drifloon", "ace"),
    K("dark_ace", "악 엘리트", "Dark Ace", "ace_trainer veteran", ANY, N,
      "houndour sneasel absol pawniard zorua deino scraggy sandile impidimp murkrow", "ace"),
    K("steel_ace", "강철 엘리트", "Steel Ace", "ace_trainer veteran", MOUNTAIN + BADLANDS, None,
      "magnemite skarmory aron beldum bronzor shieldon klink honedge pawniard tinkatink orthworm", "ace"),
    K("fairy_ace", "페어리 엘리트", "Fairy Ace", "ace_trainer mega_trainer", FLORAL + MAGICAL, None,
      "clefairy togepi ralts snubbull flabebe spritzee swirlix mimikyu hatenna impidimp fidough", "ace"),
]
