screen = <profile> [LIGHTING] [SHADOWS] [COLOR] [FOG]
screen.columns = 2
screen.LIGHTING = EXPOSURE BLOCKLIGHT_STRENGTH NIGHT_BRIGHTNESS
screen.SHADOWS = shadowMapResolution SHADOW_SAMPLES SHADOW_SOFTNESS
screen.COLOR = SATURATION BLOOM_STRENGTH
screen.FOG = FOG_STRENGTH GROUND_FOG_STRENGTH CAVE_FOG_STRENGTH BIOME_FOG_STRENGTH GROUND_FOG_HEIGHT GROUND_FOG_SAMPLES

screen.LIGHTING.columns = 1
screen.SHADOWS.columns = 1
screen.COLOR.columns = 1
screen.FOG.columns = 1

sliders = EXPOSURE BLOCKLIGHT_STRENGTH NIGHT_BRIGHTNESS SHADOW_SOFTNESS SATURATION BLOOM_STRENGTH FOG_STRENGTH GROUND_FOG_STRENGTH CAVE_FOG_STRENGTH BIOME_FOG_STRENGTH GROUND_FOG_HEIGHT

profile.SOFT = SHADOW_SAMPLES=4 SHADOW_SOFTNESS=1.5 BLOOM_STRENGTH=0.04 GROUND_FOG_SAMPLES=2
profile.COZY = SHADOW_SAMPLES=4 SHADOW_SOFTNESS=1.8 BLOOM_STRENGTH=0.07 GROUND_FOG_SAMPLES=4
profile.HIGH = SHADOW_SAMPLES=8 SHADOW_SOFTNESS=2.2 BLOOM_STRENGTH=0.08 GROUND_FOG_SAMPLES=6

uniform.float.lumavaleBiomeDry = smooth(201, if(in(biome_precipitation, 0), 1.0, 0.0), 10, 10)
uniform.float.lumavaleBiomeRainy = smooth(202, if(in(biome_precipitation, 1), 1.0, 0.0), 10, 10)
uniform.float.lumavaleBiomeSnowy = smooth(203, if(in(biome_precipitation, 2), 1.0, 0.0), 10, 10)
uniform.float.lumavaleSkyExposure = smooth(204, eyeBrightness.y / 240.0, 5, 8)

shadow.enabled = true
clouds = fancy
oldLighting = false
