"""Generates the wiki's wild trainer list, server-wiki/assets/data/trainers.js, from the trainer kinds
(tools/wild-trainers/kinds.py), the League's generated trainer definitions (tier, BP) and Cobblemon's Korean
Pokemon names. Rerun it after tools/wild-trainers/gen_wild_trainers.py.

    python tools/server-wiki/gen_trainers.py [--cobblemon JAR]
"""
import argparse, json, pathlib, re, sys, zipfile

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(REPO / "tools" / "wild-trainers"))
from biomes import TAGS  # noqa: E402
from kinds import ACE, NORMAL  # noqa: E402

NS = "more_cobblemon_contents_league_challenge"
DEFINITIONS = REPO / "mods/more-cobblemon-contents-league-challenge/src/main/resources/data" / NS / "league-challenge/wild_trainers"
OUT = REPO.parent / "server-wiki" / "assets" / "data" / "trainers.js"
DEFAULT_JAR = REPO.parent / "develop-product/client/mods/Cobblemon-fabric-1.8.1+1.21.1.jar"
TIME = {"day": "낮", "night": "밤", None: "언제나"}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cobblemon", default=str(DEFAULT_JAR))
    args = parser.parse_args()
    with zipfile.ZipFile(args.cobblemon) as jar:
        lang = jar.read("assets/cobblemon/lang/ko_kr.json").decode("utf-8")
    names = dict(re.findall(r'"cobblemon\.species\.([a-z0-9]+)\.name"\s*:\s*"([^"]*)"', lang))
    out = []
    for kind in NORMAL + ACE:
        definition = json.loads((DEFINITIONS / f"{kind['id']}.json").read_text(encoding="utf-8"))
        biomes = []
        for biome in kind["biomes"]:
            key = biome.split(":", 1)[1]
            assert key in TAGS, f"No Korean name for biome tag {biome}"
            biomes.append(TAGS[key])
        out.append({
            "id": kind["id"],
            "name": kind["ko"],
            "tier": "에이스" if definition["tier"] == "ace" else "일반",
            "bp": definition["bp"],
            "biomes": sorted(set(biomes), key=biomes.index),
            "time": TIME[kind["time"]],
            "pokemon": [names.get(s, s) for s in kind["species"]],
        })
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("/* Generated by tools/server-wiki/gen_trainers.py from the wild trainer kinds; do not edit. */\n"
                   "window.WIKI_TRAINERS = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n", encoding="utf-8")
    print(f"{len(out)} trainer kinds -> {OUT.relative_to(REPO)}")


main()
